### ISSUE TITLE
Could you transfer it to WordPress plugin？

### ISSUE THREAD

**Issue by ajmz** [andyredfern/dynalist_api_php_wrapper#1]
Could you transfer it to WordPress plugin？
thx.

**Comment by andyredfern** [comment]
Should be possible. What do actually want the WP Plugin to do?

**Comment by ajmz** [comment]
Thanks for reply.
The outliner structure in the article, such as workflowy or dynalist, become a PHP plugin of WordPress, may be very cool for our own WordPress site.
